### PR TITLE
Initial effort to support revamped ZDF mediathek.

### PR DESCRIPTION
**Pull request by jocki84**
After looking at the ZDF mediathek JSON API I got carried away and created this version. It's almost completely untested and doesn't support searching yet.

### CODE REVIEW

**Comment by jocki84** [comment]
Most obviously, this version needs to add some paging because categories with lots of videos take *ages* to load.

**Comment by raptor2101** [comment]
I will reject this Pull request, because I "extend" the underling classes to only load the target jsons (including the stream link) if the user select the movie, bit with your permission i will take the "menu-listing" from you code :)

thanks for your support anyway (kudo...)

**Comment by jocki84** [comment]
sure, use whatever is useful -- that's what open source is for :)

**Comment by raptor2101** [comment]
if you have time, you could give me feedback how the new version runs on you platform (in terms of loading speed, bugs ...)

**Pull request closed without merging**
